# You can use `az ad sp create-for-rbac --sdk-auth` to create service principal credentials
# You can set AZURE_CREDENTIALS values with multiple line secrets
# Here is an example
# - name: AZURE_CREDENTIALS
#   value: |
#      {
#       "clientId": "<clientId>",
#       "clientSecret": "<clientSecret>",
#       "subscriptionId": "<subscriptionId>",
#       "tenantId": "<tenantId>",
#       "activeDirectoryEndpointUrl": "https://login.microsoftonline.com",
#       "resourceManagerEndpointUrl": "https://management.azure.com/",
#       "activeDirectoryGraphResourceId": "https://graph.windows.net/",
#      }
#   description: Azure Credentials used for workflows.
- name: AZURE_CREDENTIALS
  value: ""
  description: Azure Credentials used for workflows in azure.websphere-traditional.image.
- name: CLIENT_ID
  value: ""
  description: Client ID for an Azure AD application registered in the Partner Center
- name: ENTITLED_IBM_USER_ID
  value: ""
  description: User name for entitled IBMid
- name: ENTITLED_IBM_USER_PWD
  value: ""
  description: Password for entitled IBMid
- name: PERSONAL_ACCESS_TOKEN
  value: ""
  description: Personal access token for the GitHub account
- name: SECRET_VALUE
  value: ""
  description: Secret value of the Azure AD application registered in the Partner Center
- name: TENANT_ID
  value: ""
  description: Tenant ID of the Azure AD application registered in the Partner Center
- name: UNENTITLED_IBM_USER_ID
  value: ""
  description: User name for unentitled IBMid
- name: UNENTITLED_IBM_USER_PWD
  value: ""
  description: Password for unentitled IBMid
- name: USER_NAME
  value: ""
  description: User name of GitHub account
- name: VM_ADMIN_ID
  value: ""
  description: User name for VM/Admin account
- name: VM_ADMIN_PASSWORD
  value: ""
  description: Password for VM/Admin account
